#!/bin/bash
PASS=$1
make clean
make html
cd docs/_build
tar -cvf docs.tar html
scp docs.tar -r anaaktge@pi.cs.oswego.edu:/home/anaaktge/public_html/ $PASS                                                            
